# Generated by Django 3.2.18 on 2023-02-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hiitbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.CharField(max_length=10)),
                ('focus', models.CharField(max_length=50)),
                ('time', models.DateTimeField(max_length=10)),
                ('slots', models.SmallIntegerField()),
            ],
        ),
    ]
