# Generated by Django 3.2.18 on 2023-02-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hiitbook_spaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='hittclasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('trainer', models.CharField(max_length=10)),
                ('focus', models.CharField(max_length=50)),
                ('time', models.DateTimeField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='hiitbook',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='hiitbook',
            name='spaces',
        ),
        migrations.RemoveField(
            model_name='hiitbook',
            name='trainer',
        ),
    ]
