# Generated by Django 3.2.18 on 2023-02-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230222_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hittclasses',
            name='time',
        ),
    ]
