# Generated by Django 3.2.18 on 2023-02-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_hittclasses_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('trainer', models.CharField(max_length=10)),
                ('focus', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
